#################################################################################################
#  Interface for the Growth and Yield Model
#  Author: Cristian R. Montes
#  Date  : January 3rd, 2020
#################################################################################################
library(shiny)
library(shinythemes)

shinyUI(fluidPage(
  theme = shinytheme("united"),
  
  # Application title
  titlePanel(title = "PMRC 1996 model",
             windowTitle = "University of Georgia -  Warnell School of Forestry"),

  sidebarLayout(
    sidebarPanel(
      tabsetPanel(tabPanel("Stand Variables", 
                            selectInput("Location", "Location",
                                       c("Piedmont",
                                         "Upper Coastal Plain",
                                         "Lower Coastal Plain"),
                                       selected = 3),
                           sliderInput("Age",
                                       "Simulation Horizon (years):",
                                       min = 1,
                                       max = 35,
                                       value = c(5,35)),
                           selectInput("SI",
                                       "Stand Productivity Measurement:",
                                       c("Dominant Height","Site Index")),
                           sliderInput("Hi",
                                       "Stand Dominant Height (ft):",
                                       min = 1,
                                       max = 105,
                                       value = 18,
                                       step  = .5),
                           sliderInput("N0",
                                       "Stand Density (trees/acre):",
                                       min = 200,
                                       max =1200,
                                       value = 822,
                                       step  = 1),
                          tags$div(title = "If you don't know the initial BA leave this at 0",
                          sliderInput("BA0",
                                      "Initial Basal Area (sq ft/acre):",
                                      min = 0,
                                      max = 250,
                                      value = 0,
                                      step = 1)),
                          tags$div(title = "This is only for Piedmont sites",
                          sliderInput("PHWD",
                                      "Hardwood proportion",
                                      min =   0,
                                      max = 100,
                                      value = 0,
                                      step = 1)),

                           helpText("The G&Y Simulator is based on PMRC's 1996 Loblolly pine model.  Developed by Cristian R. Montes. Athens, 2018.")),
                  tabPanel("Thinnings and Fertilization",
                           #checkboxInput("chk1",
                           #               "Thinning?",
                           #              value = FALSE),
                           selectInput("thin_type",
                                       "Thin type:",
                                       c("None", "Row thinning","Selective thinning")),
                           sliderInput("ThAge",
                                        "Thinning Age:",
                                        min = 5,
                                        max = 35,
                                        value = 0),
                           sliderInput("ThinDens",
                                       "Density after Thinning:",
                                        min = 0,
                                       max = 1200,
                                       value = 1200),
                           sliderInput("NFertAge",
                                       "N and P fertilization Age:",
                                       min = 0, 
                                       max = 35,
                                       value = 0),
                           sliderInput("NFert",
                                       "Nitrogen Fertilization Dose",
                                       min =   0,
                                       max = 300,
                                       value = 0),
                           checkboxInput("somevalue", "Phosphorus fertilization", FALSE),
                           helpText("Only one thinning is allowed in this model, assumed to be from bellow.")),
                  tabPanel("Products",
                           sliderInput("specPr1",
                                       "Pulp diameters (tops - min DBH):",
                                       min   = 1,
                                       max   = 10,
                                       value = c(3,4),
                                       post  = " in"),
                           
                           sliderInput("specPr2",
                                       "Chip n Saw diameters (tops - min DBH):",
                                       min = 1,
                                       max = 10,
                                       value = c(6,8),
                                       post  =" in"), 
                           
                           sliderInput("specPr3",
                                       "Sawtimber diameters (tops - min DBH):",
                                       min   = 5,
                                       max   = 12,
                                       value = c(8,10),
                                       post  = " in"),

                           helpText("Products are characterized by a minimum top diameter and a minimum treshold DBH.")),
                  tabPanel("Diameter Distribution",
                           selectInput("sel_ST",
                                       "Stand Table Source",
                                       c("Diameter Distribution",
                                        "File")),
                           fileInput("file1", "Choose CSV File",
                                     multiple = TRUE,
                                     accept = c("text/csv",
                                                "text/comma-separated-values,text/plain",
                                                ".csv")),
                           helpText("Initial Stant table can be supplied as a comma separated values in a table with two rows, one for the diameter class in inches, one for the number of trees per class"))

                 
      )),
      
    # Show a plot of the generated distribution
    mainPanel(
      tabsetPanel(id = "my_outputs",
                  tabPanel("Dominant Height", plotOutput("SIPlot"),
                           helpText("The dashed line represents the non thinned counterpart for the management regime.  Initial density for this scenario corresponds to the remaining trees from the thinned scenario. Dominant height calculated as the average height of dominant and co dominant trees.")),
                  tabPanel("Survival", plotOutput("SurvivalPlot")),
                  tabPanel("Basal Area", plotOutput("BasalArea")),
                  tabPanel("Volume",
                           plotOutput("Volume"),
                           #plotlyOutput("VolGrowth"),
                           helpText("The dashed line represents a base scenario for a site index 60ft, 850 tpa at year 0 without any thinnings.")),
                  tabPanel("Dry Weight", plotOutput("DryWeight"),
                           helpText("The dashed line represents a base scenario for a site index 60ft, 850 tpa at year 0 without any thinnings.")),
                  tabPanel("Diameter", plotOutput("QMD"),
                           helpText("The dashed line represents a base scenario for a site index 60ft, 850 tpa at year 0 without any thinnings.")),
                  tabPanel("Extraction", plotOutput("Extraction")),
                  tabPanel("Yield Table", 
                           downloadButton("downloadData", "Download"),
                           tableOutput("Yield.Table")),
                  tabPanel("Diameter Distribution",
                           sliderInput("cstDistributionAge",
                                       "Distribution Age:",
                                       min = 1,
                                       max = 35,
                                       value = 5),
                           plotOutput("Distribution")))
  )
)))